### ISSUE TITLE
How to use binding with addVertex

### ISSUE THREAD

**Issue by kapsoft** [jbmusso/gremlin-javascript#22]
Hi,

Great work here. Thanks fro doing this. 
I have a question on how to use binding with addVertex.

If I put in script without bindings (and execute with your client) like:

var searchScript =  "graph.addVertex('name', 'Dean Kaplan')";

Result is something like I expect:

[{"id":8248,"label":"vertex","type":"vertex","properties":{"name":[{"id":"1zb-6d4-3yd","value":"Dean Kaplan"}]}}]

But if I use bindings:

pairs = "'name', 'Dean Kaplan'";
var searchScript =  "graph.addVertex(x)";
return module.exports.execute(searchScript, {x:pairs}, callback);

I get:

[{"id":12360,"label":"'name', 'Dean Kaplan'","type":"vertex","properties":{}}]

puts parameter into label....something obvious I'm doing wrong? 

Thanks in advance.

Dean

**Comment by jbmusso** [comment]
This is expected, considering the way you're crafting the Gremlin query. Let me explain.

In your second attempt, you're actually calling `addVertex()` with a single argument, rather than two arguments just as you successfully did in the first attempt (without bindings).
What you're doing in the second attempt is sending the full `"'name', 'Dean Kaplan'"` String as `x` binding, and calling `addVertex(x)` with that single String as a single argument. This results in a single vertex being added with the supplied string as the vertex label.

You should try the following:

```javascript
var name = "Dean Kaplan";
var searchScript = "graph.addVertex('name', x)";
return module.exports.execute(searchScript, {x: name}, callback);
```
