### ISSUE TITLE
Gremlin Native JavaScript Stringification

### ISSUE THREAD

**Issue by guyellis** [jbmusso/gremlin-javascript#41]
Do you think that there's any value in creating a JavaScript Native API for Gremlin? Under the hood this would do a stringification of the fluent commands to generate the code to execute. So the quick start would look something like this:

```js
import { createGraph } from 'gremlin';

const g = createGraph();

g.V().has('name', 'Alice').execute((err, results) => {
  if (err) {
    return console.error(err)
  }

  console.log(results);
});

// Or with "sugar" any method that accepted a variable number of pairs of
// parameters could also accept an object a la:
const q = {name: 'Alice'};
g.V().has(q).execute((err, results) => {
...
```

WDYT?

**Comment by jbmusso** [comment]
I like this idea, but it's somewhat tricky to implement.

I tried to do that with https://github.com/jbmusso/gremlin-script (dependency of https://github.com/jbmusso/grex which is a client for TP 2.x graphs). Code is old and maybe ugly, I did this a while ago.

I see several problems:
* You must maintain/add new steps as they are added to TP3. I think there's a way to dynamically retrieve the list of Gremlin steps, so this could be done at startup time.
* You also have to maintain different function signature, which is not trivial.
* There's also an issue in that any Groovy is valid Gremlin, so we'd have to support a lot of non-Gremlin methods as well.

I think a nice way to implement this would be to use [https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Proxy](Proxy objects). We would not have to care about maintaining any specific Gremlin or Groovy methods as anything would be handled by the `Proxy` object.
I also think that having that `Proxy` return a `Promise` would be awesome. Basically, if using `async`/`await` keywords, one could do:

```javascript
const g = createGraph();

const getAlices = async () => {
  const alices = await g.V().has('name', 'Alice');
  return alices;
}
```
Coupled with a client in session mode, this is certainly neat :).

Also, we need to find a way to handle bound parameters. This is tricky as there is no way to tell which parameters should be bound or not (it depends on the steps/methods and basically only the developer can tell). In the above query, should we bind `name`, `Alice` or both? A human can easily tell, but I sense that there's no way to generalize this. Using a special wrapper function could help (ie `bound()`) could help:

```javascript
// Within an async function
const users = await g.V().has('name', bound('Alice'));
```
We would then be able to tell that we specifically want `Alice` string to be sent as a bound parameter.


Regarding parameters and sugar (function signatures), we may face situations where passing a Map as a first parameter is also valid. This may not be the case for Gremlin steps, but this can happen for Groovy methods.

Also, I'm unsure how to handle some operators. For example, the JavaScript `...` spread operator and its Groovy counterpart `*`.
The following is valid GremlinGroovy:
```groovy
g.V().has(*['name', 'Alice'])
```
The JavaScript equivalent is:
```javascript
g.V().has(...['name', 'Alice'])
```
I'm unsure how to handle this scenarios :).

**Comment by guyellis** [comment]
Thanks for taking the time for such a comprehensive reply @jbmusso - I can see the challenges in doing this now. I agree that Proxies would definitely be the way to go with this. Good example!

**Comment by PommeVerte** [comment]
String manipulation around gremlin queries is a pain. I deal with it daily in the context of an ORM/OGM and there is no easy way of implementing it (and we have native magic setters and getters akin to `Proxy` + auto generate signatures from the javadocs ... and still have issues).

Few tough examples : `where(not(__.within(["a",b])))` or `m=32L; g.V().has(id, neq(m))`  (notice how `id` is a static token and `m` neither string nor bound). Not to mention the entire TP3 API or native APIs like for titan.

 It also feels like it's outside of the scope of a simple driver and more within the realms of a query builder (but that's just me).

**Comment by jbmusso** [comment]
I've been thinking about implementing a simple solution that'd leverage [webpack loaders](https://webpack.github.io/docs/loaders.html). Basically, you'd define the following `users.gremlin` file:

```groovy
// users.gremlin
def fetchAll = { userName ->
  g.V().has('name', userName)
}

def fetchFirst = { userName ->
  g.V().has('name', userName).limit(1);
}

// Define as many functions as you want...
```
The gremlin loader would parse this file, find functions and return a JavaScript `Object<String, Function>`.
Any Groovy function defined within that file would then be imported as a JavaScript function that, when called, would simply send the Groovy function definition to Gremlin Server, with arguments sent as bound parameters (this shouldn't be too hard). Such function would either take a `callback` as last parameter or return a `Promise`:
```javascript
// 'userQueries' object would be an Object<String, Function>
// Ie. { fetchAll: [function], fetchFirst: [function] }
import userQueries from './users.gremlin';

import { createClient, bindForClient } from 'gremlin'; 

const client = createClient(8182, 'localhost');

// bindForClient would need to be implemented. Its responsibility would be to wrap these functions
// so they get executed against the proper Gremlin Server
const Users = bindForClient(userQueries, client); 

// Then do either:
Users.fetchAll('Alice', (err, results) => {
  // handle err or results
});

// or
Users.fetchFirst('Alice').then((result) => {
  // handle result
})
.catch((err) => {
  // handle err
});

// or, within an async function:
try {
  const alices = await Users.fetchAll('Alice');
} catch(e} {
  // handle error
}
```

The benefits of this approach are:
* any `.gremlin` file you write is still valid Gremlin-Groovy, so anything in there would be reusable directly in the Gremlin Console or in any other application - maximum reusability
* you also get proper syntax highlighting in your IDE since you're writing valid Groovy
* you could also decide to have these `.gremlin` files loaded as server side Gremlin scripts when in production (send full function body + call to that function in dev mode, only send call to that function in production).
* it shouldn't be too hard to write DSLs in JavaScript and do nice chains with high level `Observable`/`Streams` libraries such as RxJS or Bacon. With chains, we're basically doing custom/domain-specific Traversals.
* you decouple your code from what you want to get ("users") to how you want to fetch these (with "gremlin queries", which is an implementation detail)

This is one of the reason I like Gremlin: it's a DSL, not a language. Steps are functions, and we developers are accustomed to functions. Chaining is easy. This allows for instant cool things like this.

Actually, as I'm writing this, I'm thinking that these functions could return anonymous traversals, allowing easier chaining. Hmmm. :thought_balloon: .

**Comment by jbmusso** [comment]
About that webpack loader, there may be interesting things to do with https://github.com/chiquitinxx/grooscript ("Converts your Groovy code to Javascript").

**Comment by jbmusso** [comment]
I spent some time tinkering with webpack loaders and I just published an experimental version of `gremlin-loader`: https://www.npmjs.com/package/gremlin-loader

**Comment by guyellis** [comment]
Thanks @jbmusso - I hope to circle back and look at this in more detail in the next couple of weeks.

**Comment by PommeVerte** [comment]
pretty cool stuff.

**Comment by jbmusso** [comment]
I closed this issue as it's outside of the scope of the driver, though I'm open to continue this conversation here.

**Comment by davidcrouch** [comment]
I've pretty much implemented what guyellis is asking for and can also confirm the pain mentioned by PommeVerte. I developed it as part of a higher-level ORM implementation and only implemented the steps that I needed, which was about 30% of all TP3 steps. 

It works and is a hack, but maintenance will be a pain and I don't think it is a smart strategy for the long term due to different TP release support not to mention the limitations with regard to supporting the Groovy language in general (not an issue for me though). 

Just my $0.02.

**Comment by jbmusso** [comment]
Referencing a recent discussion on this topic posted on the Gremlin users mailing list: https://groups.google.com/d/topic/gremlin-users/kTXEzJE8wEs/discussion
